spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luckdraw?characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  type-aliases-package: dao.model
  mapper-locations: classpath:mapper/*.xml