spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luckdraw?characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 5
    minEvictableIdleTimeMillis: 60000
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    maxWait: 60000
    filters: stat,wall,log4j
mybatis:
  type-aliases-package: dao.model
  mapper-locations: classpath:mapper/*.xml
logging:
  level: debug
